name: sosang
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  date_format: ^2.0.2
  logger: ^1.0.0
  intl: "0.19.0"
  get_it: ^7.2.0
  sprintf: ^7.0.0
  shared_preferences: ^2.2.2
  window_manager: ^0.3.9
  encrypt: ^5.0.3
  flutter_dotenv: ^5.0.2
  defer_pointer: ^0.0.2
  indexed: ^0.0.8
  styled_text: ^8.1.0
  dropdown_button2: ^2.0.0
  hovering: ^1.0.4
  audioplayers: ^6.1.0
  path_provider: ^2.1.4
  gallery_saver: ^2.3.2
  image_gallery_saver: ^2.0.3
  lottie: ^2.2.0
  image: ^4.2.0
  jpeg_encode: ^1.0.1
  camera: ^0.11.0+2
  camera_windows: ^0.2.5
  camera_platform_interface: ^2.8.0
  shelf: ^1.4.1
  shelf_router: ^1.1.4
  shelf_cors_headers: ^0.1.5
  event_bus: ^2.0.1
  win32: ^5.7.2
  device_info_plus: ^9.0.3
  fl_chart: ^0.69.0
  flutter_speech: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/img/
    - assets/sounds/camera.mp3
    - assets/lottie/

  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Thin.ttf
          weight: 100
        - asset: assets/fonts/Pretendard-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Pretendard-Light.ttf
          weight: 300
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
        - asset: assets/fonts/Pretendard-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Pretendard-Black.ttf
          weight: 900
